# Generated by Django 5.0.1 on 2025-02-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='item_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='item_type',
            field=models.CharField(default='service', max_length=50),
        ),
    ]
