# Generated by Django 5.0.1 on 2025-03-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='more_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='more_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upto',
            name='more_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
