# Generated by Django 5.0.1 on 2025-03-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0002_combo_more_details_services_more_details_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
    ]
