# Generated by Django 5.0.1 on 2025-01-26 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0003_productscheme_user_productscheme_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productscheme',
            name='username',
        ),
        migrations.AlterField(
            model_name='productscheme',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EPI_App.profile'),
        ),
    ]
