# Generated by Django 5.0.1 on 2025-01-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0006_alter_productscheme_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productscheme',
            name='user',
        ),
        migrations.AlterField(
            model_name='productscheme',
            name='username',
            field=models.CharField(default='default_user', max_length=150),
        ),
    ]
