# Generated by Django 5.0.1 on 2025-01-26 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0007_remove_productscheme_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productscheme',
            name='username',
        ),
        migrations.AddField(
            model_name='productscheme',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EPI_App.profile'),
        ),
    ]
