# Generated by Django 5.0.1 on 2025-01-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0008_remove_productscheme_username_productscheme_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_his',
            name='product_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productscheme',
            name='product_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='product_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
