# Generated by Django 5.0.1 on 2025-03-28 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0009_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
