# Generated by Django 5.0.1 on 2025-03-28 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0010_delete_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EPI_App.profile'),
        ),
    ]
