# Generated by Django 5.0.1 on 2025-01-27 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0010_remove_payment_payment_date_payment_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=200, null=True, unique=True)),
                ('investments', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('backcount', models.IntegerField(default=0, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EPI_App.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='pay_his',
        ),
    ]
