# Generated by Django 5.0.1 on 2025-01-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0011_plans_delete_pay_his'),
    ]

    operations = [
        migrations.CreateModel(
            name='pay_his',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=200, null=True, unique=True)),
                ('investments', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('backcount', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Plans',
        ),
    ]
