# Generated by Django 5.0.1 on 2025-01-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0012_pay_his_delete_plans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pay_his',
        ),
    ]
