# Generated by Django 5.0.1 on 2025-01-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0014_alter_productscheme_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscheme',
            name='product_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
