# Generated by Django 5.0.1 on 2025-01-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0015_alter_productscheme_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount_paid',
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
