# Generated by Django 5.0.1 on 2025-02-02 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0020_investment_delete_referrals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='timestamp',
        ),
    ]
