# Generated by Django 5.0.1 on 2025-02-02 20:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0021_remove_investment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
