# Generated by Django 5.0.1 on 2025-02-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0022_investment_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
