# Generated by Django 5.0.1 on 2025-02-02 21:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0023_alter_investment_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
