# Generated by Django 5.0.1 on 2025-02-06 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0024_investment_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rewards_earned',
        ),
    ]
