# Generated by Django 5.0.1 on 2025-02-06 07:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0025_remove_profile_rewards_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rewards_earned',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
