# Generated by Django 5.0.1 on 2025-02-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0026_profile_rewards_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='balance_at_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
