# Generated by Django 5.0.1 on 2025-02-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0027_payment_balance_at_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='balance_at_payment',
        ),
    ]
