# Generated by Django 5.0.1 on 2025-02-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0029_paymentorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='product_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
