# Generated by Django 5.0.1 on 2025-02-09 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0030_paymentorder_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EPI_App.profile'),
        ),
    ]
