# Generated by Django 5.0.1 on 2025-02-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0032_profile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('mobiles', 'Mobiles'), ('home_kitchen', 'Home & Kitchen'), ('fashion', 'Fashion'), ('books', 'Books'), ('others', 'Others')], default='others', max_length=20),
        ),
    ]
