# Generated by Django 5.0.1 on 2025-02-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0033_services_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
