# Generated by Django 5.0.1 on 2025-02-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0034_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.CharField(max_length=500, null=True)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('mobiles', 'Mobiles'), ('home_kitchen', 'Home & Kitchen'), ('fashion', 'Fashion'), ('books', 'Books'), ('others', 'Others')], default='others', max_length=20)),
            ],
        ),
    ]
