# Generated by Django 5.0.1 on 2025-02-18 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0037_remove_services_img_serviceimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='img',
        ),
        migrations.CreateModel(
            name='ComboImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('Combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='EPI_App.combo')),
            ],
        ),
    ]
