# Generated by Django 5.0.1 on 2025-02-21 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPI_App', '0038_remove_combo_img_comboimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('desc', models.CharField(max_length=500, null=True)),
                ('category', models.CharField(choices=[('kids', 'Kids'), ('teens', 'Teens'), ('youths', 'Youths'), ('others', 'Others')], default='others', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UptoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('upto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='EPI_App.upto')),
            ],
        ),
    ]
